spring.database.driverClassName: "com.mysql.cj.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://localhost/rollingstone"
spring.datasource.username: "root"
spring.datasource.password: "root"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"
spring.jpa.hibernate.ddl-auto: "update"
